version: "2.4"
networks:
  custom-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/16
          gateway: 172.11.0.1
services:
  databs:
    image: postgres:15
    mem_limit: 1024m
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/lanplay/University/testvol:/var/lib/postgresql/data
    networks:
      - custom-network

  backend_cur:
    image: backend_ok:1.0.1
    restart: always
    mem_limit: 512m
    ports:
      - "7777:7777"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_URL: "jdbc:postgresql://databs:5432/currency"
      API_KEY: ${API_KEY}
      URL_KEYCLOAK: http://192.168.100.206:8080
    volumes:
      - ./logs/:/logs/
    depends_on:
      - databs
    networks:
      - custom-network

  frontend_cur:
    image: frontend_angular:1.0.1
    restart: always
    ports:
      - "4200:80"
    volumes:
      - /home/lanplay/University/Arqui/front/testing1/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend_cur
    networks:
      - custom-network





