version: "2.4"
services:
  databs:
    image: postgres:15
    mem_limit: 1024m
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/lanplay/University/testvol:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    mem_limit: 512m
    ports:
      - "7777:7777"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_URL: "jdbc:postgresql://databs:5432/currency"
      API_KEY: ${API_KEY}
    depends_on:
      - databs


