version: "2.4"
services:
  databs:
    image: postgres:15
    mem_limit: 1024m
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: mypass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/lanplay/University/testvol:/var/lib/postgresql/data
    networks:
      - MyNetwork

  backend:
    build: .
    restart: always
    mem_limit: 512m
    ports:
      - "7777:7777"
    environment:
      PASSWORD: mypass
      URL: "jdbc:postgresql://databs:5432/currency"
      API_KEY: ${API_KEY}
    depends_on:
      - databs
    networks:
      - MyNetwork

  angular:
    image: angular:4.0.1-docker
    environment:
      BACKEND_URL: backend
    depends_on:
      - backend
    ports:
      - "4200:80"
    volumes:
      - /home/lanplay/University/Arqui/front/testing1/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - MyNetwork
networks:
  MyNetwork:
    name: mylanNet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"
          gateway: 172.23.0.1