api:
  key: ${API_KEY}
  url: "https://api.apilayer.com/exchangerates_data/convert"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: optional:file:.env[.properties]
  application:
    name: currency-converter
  jpa:
    hibernate:
      ddl-auto: update

  
server:
  port: 7777

keycloak:
  config:
    import: optional:file:.env[.properties]
  realm: testing2
  auth-server-url: ${URL_KEYCLOAK}
  autodetect-bearer-only: true
  ssl-required: external
  resource: backend
  credentials:
    secret: J82JDRDUaIyMABThMlFGvQid1jsULeG5
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          methods:
            - GET
          patterns:
            - /api/v1/currency/all
    - auth-roles:
        - USER
      security-collections:
        - name: SERVICIOS DEL USUARIO
          methods:
            - GET
          patterns:
            - /api/v1/currency/convert
