api:
  key: jqPB058UIYBeQoPFJNMfd73RtwJEjFcK
  url: "https://api.apilayer.com/exchangerates_data/convert"
spring:
  datasource:
    driver-class-name: org.postgresql.jdbc2.optional.SimpleDataSource
    url: ${URL:jdbc:postgresql://localhost:5432/recordsCurrencyKotlin}
    username: ${USERNAME:postgres}
    password: ${PASSWORD:1234}
  application:
    name: currency-converter
  jpa:
    hibernate:
      ddl-auto: update

  
server:
  port: 7777
