api:
  key: ${API_KEY}
  url: "https://api.apilayer.com/exchangerates_data/convert"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: optional:file:.env[.properties]
  application:
    name: currency-converter
  jpa:
    hibernate:
      ddl-auto: update

  
server:
  port: 7777

keycloak:
  realm: Software
  auth-server-url: http://localhost:8080
  autodetect-bearer-only: true
  ssl-required: external
  resource: Back
  credentials:
    secret: mE7YQIqHrQvJoV5EUcqeto1Fad0JKqY5
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          methods:
            - GET
          patterns:
            - /api/currency/*