api:
  key: ${API_KEY}
  url: "https://api.apilayer.com/exchangerates_data/convert"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: optional:file:.env[.properties]
  application:
    name: currency-converter
  jpa:
    hibernate:
      ddl-auto: update

  
server:
  port: 7777
