api:
  key: jqPB058UIYBeQoPFJNMfd73RtwJEjFcK
  url: "https://api.apilayer.com/exchangerates_data/convert"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL:jdbc:postgresql://172.17.0.1:5432/currency}
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mypass}
  application:
    name: currency-converter
  jpa:
    hibernate:
      ddl-auto: update

  
server:
  port: 7777
